### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'lang'

### ISSUE THREAD

**Issue by TheRockettek** [rominf/profanity-filter#20]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/profanity_filter/profanity_filter.py", line 154, in __init__
    spells=spells,
  File "/usr/local/lib/python3.6/dist-packages/profanity_filter/profanity_filter.py", line 180, in config
    self._set_languages(languages, load_morphs=morphs is None, load_nlps=nlps is None, load_spells=spells is None)
  File "/usr/local/lib/python3.6/dist-packages/profanity_filter/profanity_filter.py", line 418, in _set_languages
    self.morphs = None
  File "/usr/local/lib/python3.6/dist-packages/profanity_filter/profanity_filter.py", line 319, in morphs
    self._morphs[language] = MorphAnalyzer(lang=language)
TypeError: __init__() got an unexpected keyword argument 'lang'
```

**Comment by rominf** [comment]
I think you've installed the `pymorphy2` from PyPI, but not from the git. Please uninstall it and follow https://github.com/rominf/profanity-filter#pymorphy2

**Comment by rominf** [comment]
@TheRockettek, is the problem solved?

**Comment by TheRockettek** [comment]
Oh yeah it did work. Sorry, forgot to respond.
