### ISSUE TITLE
Not working with auto-py-to-exe

### ISSUE THREAD

**Issue by ReCore-sys** [rominf/profanity-filter#33]
So I am trying to make a bot that uses this module and it can't seem to work after being turned into a .exe. It compiles fine but if I run the .exe from the command line, this is the output:
`C:\Users\ReCor\Documents\Bot>bot.exe                                                                                    Traceback (most recent call last):                                                                                        File "bot.py", line 10, in <module>                                                                                       import better_profanity                                                                                               File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module                                               File "better_profanity\__init__.py", line 3, in <module>                                                                File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module                                               File "better_profanity\better_profanity.py", line 5, in <module>                                                        File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module                                               File "better_profanity\constants.py", line 14, in <module>                                                            FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ReCor\\AppData\\Local\\Temp\\_MEI88242\\better_profanity\\alphabetic_unicode.json'                                                                                          [22044] Failed to execute script bot  `

**Comment by rominf** [comment]
Hi!
Sorry, I don't have time to support profanity-filter on Windows.
